-- MySQL Script generated by MySQL Workbench
-- mar 05 sep 2017 13:20:43 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mini
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mini
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini` DEFAULT CHARACTER SET utf8 ;
USE `mini` ;

-- -----------------------------------------------------
-- Table `mini`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(64) NOT NULL,
  `Clave` VARCHAR(128) NOT NULL,
  `Estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo',
  `Paterno` VARCHAR(128) NOT NULL,
  `Materno` VARCHAR(128) NULL,
  `Nombres` VARCHAR(128) NOT NULL,
  `DNI` VARCHAR(12) NOT NULL,
  `FotoPerfil` VARCHAR(128) NOT NULL DEFAULT 'default.png',
  `email` VARCHAR(512) NULL,
  `movil` VARCHAR(52) NULL,
  `CreditoSMS` INT NOT NULL DEFAULT 10,
  `CreditoMail` INT NOT NULL DEFAULT 10,
  `Registrador` INT NULL,
  `code` VARCHAR(128) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(128) NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `click` TEXT NULL,
  `Visto` ENUM('Si', 'No') NOT NULL DEFAULT 'No',
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`, `idUsuario`),
  INDEX `fk_Notificacion_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Notificacion_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mini`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` TEXT NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMensaje`, `idUsuario`),
  INDEX `fk_Mensaje_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Mensaje_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mini`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini`.`DestinoMensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini`.`DestinoMensaje` (
  `idMensaje` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `Visto` ENUM('Si', 'No') NOT NULL DEFAULT 'No',
  PRIMARY KEY (`idMensaje`, `idUsuario`),
  INDEX `fk_Mensaje_has_Usuario_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Mensaje_has_Usuario_Mensaje1_idx` (`idMensaje` ASC),
  CONSTRAINT `fk_Mensaje_has_Usuario_Mensaje1`
    FOREIGN KEY (`idMensaje`)
    REFERENCES `mini`.`Mensaje` (`idMensaje`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mensaje_has_Usuario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mini`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini`.`Tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini`.`Tarea` (
  `idTarea` INT NOT NULL AUTO_INCREMENT,
  `Tarea` VARCHAR(256) NOT NULL,
  `Avance` INT NOT NULL DEFAULT 0,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idUsuario` INT NOT NULL,
  `click` TEXT NULL,
  PRIMARY KEY (`idTarea`, `idUsuario`),
  INDEX `fk_Tarea_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Tarea_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mini`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini`.`Permiso` (
  `idPermiso` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NOT NULL,
  `Modulo` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPermiso`, `idUsuario`),
  INDEX `fk_Permiso_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Permiso_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mini`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
